name: ⛅ Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install development packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev libxdo-dev
      - uses: hecrj/setup-rust-action@v2.0.1
        with:
          components: clippy
      - uses: actions/checkout@v4.2.2
      - name: Check lints
        run: cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings