name: ⛅ Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v2.0.1
        with:
          components: clippy
      - uses: actions/checkout@v4.2.2
      - name: Check lints
        run: cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings